server:
  port: ${PORT:0}

spring:
      
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ms-product
    username: sa
    password: ''
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        '[show_sql]': true
        '[use_sql_comments]': false
        '[format_sql]': false
    show-sql: true
    
  boot:
    admin:
      client:
        enabled: true
  
  zipkin:
    enabled: false
    sender:
      type: kafka
    kafka:
      topic: zipkin

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    enabled: true

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}